Vagrant.configure("2") do |config|
  config.vm.box = "rafaelfoice/centosk3s"
  config.vm.box_version = "0.1.0"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.hostname = "testcentosk3s"
  config.vm.provision :shell, path: "scripts/post_install.sh"
end